name: CI

on: push

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: "bash -n app.sh"
            - run: "bash app.sh"
